export type BlogSection = {
  heading: string;
  body: string;
};

export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  category: "Lawn Care" | "Garden Beds" | "Property Cleanup" | "Brush Clearing" | "Detailing";
  published: string;
  readTime: string;
  image: string;
  imageAlt: string;
  keywords: string[];
  lead: string;
  sections: BlogSection[];
  tips: string[];
  clmNote: string;
  faq: [string, string][];
  source?: { label: string; url: string };
};

const sources = {
  lawn: {
    label: "Oklahoma State University Extension: Lawn Management in Oklahoma",
    url: "https://extension.okstate.edu/fact-sheets/lawn-management-in-oklahoma",
  },
  turf: {
    label: "Oklahoma State University Extension: Selecting a Lawn Grass for Oklahoma",
    url: "https://extension.okstate.edu/fact-sheets/selecting-a-lawn-grass-for-oklahoma",
  },
  mulch: {
    label: "Oklahoma State University Extension: All You Need To Know About Mulch",
    url: "https://extension.okstate.edu/fact-sheets/all-you-need-to-know-about-mulch",
  },
  water: {
    label: "Oklahoma State University Extension: Water-Wise Landscape Principles",
    url: "https://extension.okstate.edu/fact-sheets/water-wise-landscape-principles-for-oklahoma-2",
  },
  storm: {
    label: "Oklahoma State University Extension: Managing Storm-Damaged Trees",
    url: "https://extension.okstate.edu/fact-sheets/managing-storm-damaged-trees",
  },
  cedar: {
    label: "Oklahoma State University Extension: Eastern Redcedar Control and Management",
    url: "https://extension.okstate.edu/fact-sheets/eastern-redcedar-control-and-management-best-management-practices-to-restore-oklahomas-ecosystems",
  },
};

export const blogPosts: BlogPost[] = [
  {
    slug: "woodward-ok-lawn-care-calendar",
    title: "A Month-by-Month Lawn Care Calendar for Woodward, Oklahoma",
    description: "A practical lawn care calendar for Woodward homeowners covering mowing, watering, cleanup, edging, and seasonal planning.",
    category: "Lawn Care",
    published: "2026-07-24",
    readTime: "7 min read",
    image: "/images/work/lawn-after.jpg",
    imageAlt: "Freshly mowed and edged lawn in northwest Oklahoma",
    keywords: ["Woodward OK lawn care", "Oklahoma lawn calendar", "seasonal lawn maintenance"],
    lead: "Northwest Oklahoma lawns do not follow a one-size-fits-all schedule. Wind, sudden temperature swings, spring growth, and summer heat all change what the property needs. A simple calendar helps you stay ahead without doing work that the lawn does not need.",
    sections: [
      { heading: "January through March: inspect and prepare", body: "Winter is the time to walk the property, note drainage problems, pick up limbs, and plan repairs. Late winter is also a good time to sharpen mower blades and inspect edging areas. As temperatures begin to rise, avoid rushing into heavy fertilizing before the grass is actively growing." },
      { heading: "April through August: mow with the weather", body: "Spring growth can arrive quickly around Woodward. Begin mowing when the lawn is actively growing, then adjust frequency instead of forcing a rigid schedule. Through summer, remove no more than roughly one-third of the blade at a time, keep blades sharp, and raise the cutting height slightly during extended heat." },
      { heading: "September through December: finish clean", body: "Late summer and fall are about steady mowing, leaf and debris removal, clean edges, and preparing beds before winter. Keep traffic off stressed areas, address bare spots at the correct time for your grass type, and finish the year with a clean final cut rather than scalping the lawn." },
    ],
    tips: ["Walk the property before every first mow of the season.", "Change mowing frequency when rainfall and growth change.", "Keep clippings off drives and sidewalks.", "Schedule storm debris removal before it damages turf underneath."],
    clmNote: "Combs Land Management helps Woodward property owners turn this calendar into a dependable routine. The crew can handle recurring mowing, seasonal cleanup, bed work, and larger property resets under one schedule.",
    faq: [["When does mowing usually begin in Woodward?", "It depends on grass type and weather, but mowing should begin after active growth starts rather than on a fixed calendar date."], ["Should I mow dormant grass?", "Usually only a cleanup cut is needed. Repeated mowing of dormant turf adds traffic without providing much benefit."]],
    source: sources.lawn,
  },
  {
    slug: "bermudagrass-mowing-woodward-summer",
    title: "How to Mow Bermudagrass Through a Woodward Summer",
    description: "Learn how mowing height, blade sharpness, timing, and cleanup help bermudagrass handle hot and windy Woodward summers.",
    category: "Lawn Care",
    published: "2026-07-17",
    readTime: "6 min read",
    image: "/images/work/lawn-before.jpg",
    imageAlt: "Residential bermudagrass lawn ready for professional mowing",
    keywords: ["bermudagrass mowing Woodward", "summer lawn care Oklahoma", "mowing height tips"],
    lead: "Bermudagrass is well suited to Oklahoma sun and heat, but even tough turf looks rough when it is cut inconsistently or with dull equipment. The goal is not simply to cut the grass shorter. The goal is to keep a dense, even canopy that shades soil and recovers quickly.",
    sections: [
      { heading: "Let growth set the schedule", body: "During warm, wet weeks, bermudagrass may need more frequent mowing. During drought or extreme heat, growth slows and the interval can stretch. Waiting until the lawn is very tall and then cutting it low creates a brown, stemmy appearance and can stress the turf." },
      { heading: "Use a clean, sharp cut", body: "A sharp mower blade leaves a narrow, clean edge. A dull blade shreds leaf tips, which gives the lawn a pale cast and increases moisture loss. Inspect the cut after each visit. Ragged ends are a sign that the blade needs attention." },
      { heading: "Finish the whole property", body: "Mowing is only part of a professional result. Trimming around fences and trees, edging hard surfaces, and blowing clippings from walks and drives create the finished look that Woodward homeowners notice from the street." },
    ],
    tips: ["Never remove a large portion of the blade in one pass.", "Avoid mowing immediately after heavy rain.", "Alternate mowing direction when the layout allows.", "Raise the cut slightly during prolonged heat and dry weather."],
    clmNote: "Combs Land Management adjusts recurring mowing to actual growth conditions across Woodward County. That means a cleaner cut, fewer scalped spots, and a final pass that leaves the entire property sharp.",
    faq: [["Why does bermudagrass look brown after mowing?", "The lawn may have been cut too low, too much growth may have been removed at once, or the mower blade may be dull."], ["Is bermudagrass a good fit for full sun?", "Yes. OSU Extension identifies bermudagrass as one of Oklahoma's best-adapted choices for sunny sites because of its heat and drought tolerance."]],
    source: sources.turf,
  },
  {
    slug: "when-to-start-mowing-woodward-spring",
    title: "When Should You Start Mowing in Spring in Woodward?",
    description: "Know the signs that your Woodward lawn is ready for its first spring mow and how to avoid an early-season scalp.",
    category: "Lawn Care",
    published: "2026-07-10",
    readTime: "5 min read",
    image: "/images/home-hero.jpg",
    imageAlt: "Lawn mower working across a green Woodward area property",
    keywords: ["first spring mow Woodward", "spring lawn care Oklahoma", "when to mow lawn"],
    lead: "A warm afternoon can make it feel like mowing season has arrived, but soil temperature and active growth matter more than one pleasant day. The first spring mow should clean and shape the lawn without cutting dormant turf down to bare stems.",
    sections: [
      { heading: "Look for consistent active growth", body: "Scattered green patches are not the same as a lawn that has broken dormancy. Wait until the dominant grass is growing across most of the property. If only winter weeds are tall, deal with the actual problem instead of repeatedly mowing dormant turf." },
      { heading: "Clear the surface first", body: "Before the mower comes out, remove sticks, rocks, storm debris, toys, and hidden wire. Walk fence lines and drainage areas where wind tends to collect material. This protects equipment and prevents debris from becoming a projectile." },
      { heading: "Make the first cut conservative", body: "Set the mower high enough to avoid scalping uneven ground. A conservative first cut reveals low spots, matted areas, and edges that need work. You can refine the height as active growth becomes more consistent." },
    ],
    tips: ["Wait for broad green-up instead of one warm weekend.", "Inspect for winter damage before mowing.", "Use a sharp blade on tender spring growth.", "Plan bed cleanup and edging at the same time for a complete reset."],
    clmNote: "Combs Land Management can handle the first full property reset in Woodward, including debris pickup, mowing, trimming, edging, and bed cleanup. Starting clean makes the rest of the season easier to maintain.",
    faq: [["Can an early mow damage the lawn?", "One careful cleanup cut is unlikely to ruin healthy turf, but repeated low mowing before active growth can expose crowns and create a thin appearance."], ["Should leaves be removed before the first mow?", "Yes. Thick, wet leaves can smother turf and interfere with an even cut."]],
    source: sources.lawn,
  },
  {
    slug: "how-often-mow-lawn-woodward-ok",
    title: "How Often Should You Mow a Lawn in Woodward, OK?",
    description: "A realistic guide to mowing frequency in Woodward based on rainfall, temperature, grass type, and the one-third rule.",
    category: "Lawn Care",
    published: "2026-07-03",
    readTime: "6 min read",
    image: "/images/work/lawn-after.jpg",
    imageAlt: "Even mowing stripes on a maintained Woodward lawn",
    keywords: ["mowing frequency Woodward OK", "weekly lawn mowing", "Oklahoma lawn service"],
    lead: "Weekly mowing is a useful baseline, not a law. A Woodward lawn may surge after spring rain, slow during a dry stretch, and pick up again when temperatures moderate. Good mowing follows growth so the lawn stays tidy without unnecessary traffic.",
    sections: [
      { heading: "Use the one-third rule", body: "Try not to remove more than about one-third of the grass blade in a single visit. If the lawn gets away from you, bring it down gradually over multiple cuts. This protects color, reduces clumping, and keeps the growing point better protected." },
      { heading: "Watch rainfall and irrigation", body: "Grass grows faster when moisture and temperature line up. A regularly irrigated lawn may need a tighter schedule than a non-irrigated property. After drought, do not assume growth will immediately return evenly across the whole yard." },
      { heading: "Match the schedule to the property", body: "Commercial entrances and highly visible front yards often need a more consistent finished appearance. Acreage, back lots, and low-use areas may follow a different interval. Dividing the property into maintenance zones can control cost while keeping the important areas sharp." },
    ],
    tips: ["Measure growth instead of relying only on the calendar.", "Avoid a low cut after missing a visit.", "Keep a consistent edge along visible hard surfaces.", "Adjust separate zones according to use and visibility."],
    clmNote: "Combs Land Management builds mowing schedules around the property, not a generic route sheet. Woodward homeowners, rentals, businesses, and acreage owners can choose recurring or single-visit service.",
    faq: [["Is weekly mowing always necessary?", "No. Weekly service is common during active growth, but conditions and the desired finish should determine frequency."], ["What if the lawn is already overgrown?", "A staged cut and cleanup is usually better than taking it extremely low in one pass."]],
    source: sources.lawn,
  },
  {
    slug: "watering-lawn-drought-wind-woodward",
    title: "Watering a Lawn During Heat, Drought, and Wind in Woodward",
    description: "Practical watering habits for Woodward lawns, including timing, deep watering, runoff checks, and drought expectations.",
    category: "Lawn Care",
    published: "2026-06-26",
    readTime: "7 min read",
    image: "/images/work/lawn-before.jpg",
    imageAlt: "Sun-exposed residential lawn during an Oklahoma dry period",
    keywords: ["watering lawn Woodward", "Oklahoma drought lawn care", "water wise landscaping"],
    lead: "Hot temperatures are only part of the moisture problem in northwest Oklahoma. Wind can increase evaporation, and compacted or sloped soil can shed water before it reaches the root zone. Better watering is about timing and infiltration, not simply running sprinklers longer.",
    sections: [
      { heading: "Water early and deeply", body: "Early morning watering reduces evaporation and gives foliage time to dry. Longer, less frequent watering usually encourages deeper roots better than a short daily sprinkle. The right amount depends on soil, grass, sun, and recent weather." },
      { heading: "Check where the water goes", body: "Watch each irrigation zone. Water hitting pavement, misting into the wind, or running down the curb is not helping the lawn. Broken heads, poor aim, compacted soil, and excessive run time can all waste water while dry spots remain." },
      { heading: "Accept seasonal dormancy when appropriate", body: "Not every lawn must remain bright green through every dry period. Healthy warm-season turf can slow or go dormant under drought stress. Decide whether your goal is survival, moderate color, or a consistently green appearance, then water accordingly." },
    ],
    tips: ["Run irrigation before sunrise when possible.", "Split watering into cycles if runoff begins.", "Check soil moisture before adding another cycle.", "Raise mowing height slightly to shade soil during heat."],
    clmNote: "Combs Land Management helps Woodward clients pair smart mowing with practical property care. The crew can identify obvious runoff, scalping, and maintenance issues during routine visits and keep beds mulched to slow moisture loss.",
    faq: [["Is daily watering best in summer?", "Usually not for established lawns. Deep, less frequent watering is often more effective, but new seed or sod follows a different establishment schedule."], ["Why are some areas dry even when sprinklers run?", "Coverage gaps, wind drift, compacted soil, slopes, and competing tree roots are common causes."]],
    source: sources.water,
  },
  {
    slug: "bermuda-vs-fescue-woodward-ok",
    title: "Bermudagrass vs. Fescue for Woodward Properties",
    description: "Compare bermudagrass and tall fescue for Woodward sun, shade, heat, water use, and maintenance expectations.",
    category: "Lawn Care",
    published: "2026-06-19",
    readTime: "7 min read",
    image: "/images/work/lawn-after.jpg",
    imageAlt: "Healthy turf surrounding a northwest Oklahoma home",
    keywords: ["bermuda vs fescue Oklahoma", "best grass Woodward", "shade grass Oklahoma"],
    lead: "The best grass is the one that fits the site and the level of care you are willing to provide. In Woodward, bermudagrass and tall fescue can both work, but they solve different problems and respond very differently to summer heat.",
    sections: [
      { heading: "Bermudagrass handles sun and heat", body: "Bermudagrass thrives in full sun, spreads aggressively, and has strong heat and drought tolerance. It is a practical choice for open lawns and high-use areas. The tradeoff is winter dormancy and poor performance in meaningful shade." },
      { heading: "Fescue brings green color to cooler and shaded areas", body: "Tall fescue can stay green through cooler seasons and tolerates more shade. It usually needs more summer water than bermudagrass and may thin during prolonged heat. Many properties use it selectively rather than across every sunny square foot." },
      { heading: "Choose by zone, not by wish", body: "Map full sun, partial shade, traffic, irrigation coverage, and drainage. A mixed property may need different solutions in different areas. Forcing one grass into every zone often creates a constant repair cycle." },
    ],
    tips: ["Count actual hours of direct sun.", "Consider summer water availability.", "Match grass choice to foot traffic.", "Plan how the lawn should look during winter dormancy."],
    clmNote: "Combs Land Management maintains both sunny and shaded Woodward properties. A clear site assessment helps the crew recommend realistic mowing and cleanup expectations for each part of the lawn.",
    faq: [["Which grass uses less water in full sun?", "Bermudagrass is generally better adapted to Oklahoma heat and has lower irrigation requirements than tall fescue."], ["Can fescue survive a Woodward summer?", "It can, especially in suitable shade and with attentive watering, but full-sun fescue usually needs more summer care."]],
    source: sources.turf,
  },
  {
    slug: "spring-lawn-cleanup-checklist-woodward",
    title: "The Woodward Spring Lawn Cleanup Checklist",
    description: "Use this spring cleanup checklist to remove winter debris, reset edges, refresh beds, and prepare your Woodward property.",
    category: "Property Cleanup",
    published: "2026-06-12",
    readTime: "6 min read",
    image: "/images/work/cleanup-after.jpg",
    imageAlt: "Clean residential yard after debris removal",
    keywords: ["spring cleanup Woodward", "yard cleanup checklist", "Oklahoma property cleanup"],
    lead: "A spring reset does more than make the yard look better. It exposes drainage trouble, removes material that can smother turf, and gives you a clear view of what actually needs repair before growth accelerates.",
    sections: [
      { heading: "Start with safety and access", body: "Walk the property before using equipment. Pick up wire, glass, rocks, branches, and material hidden in tall edges. Look overhead for damaged limbs and avoid working below anything that appears cracked, hanging, or unstable." },
      { heading: "Work from large debris to fine cleanup", body: "Remove limbs and bulky material first, then rake matted leaves and smaller debris. Finish with hard-surface cleanup. This order prevents repeated work and makes it easier to see low spots and damaged turf." },
      { heading: "Reset beds and borders", body: "Pull obvious weeds, remove dead annual growth, redefine bed edges, and inspect mulch depth. A clean border between turf and beds gives the entire property a finished appearance even before peak spring color arrives." },
    ],
    tips: ["Photograph storm damage before cleanup if insurance may be involved.", "Keep debris piles away from drives and utility access.", "Inspect downspout discharge areas.", "Schedule hauling before piles become windblown again."],
    clmNote: "Combs Land Management provides complete spring cleanup in Woodward and nearby communities. The crew can remove debris, mow, trim, edge, refresh beds, and haul material away instead of leaving another pile for the homeowner.",
    faq: [["What should be removed first?", "Start with hazardous or bulky material, then work down to leaves, small debris, and the final surface cleanup."], ["Do you haul spring debris away?", "Combs Land Management offers cleanup and removal so the finished property is actually clear."]],
    source: sources.storm,
  },
  {
    slug: "fall-lawn-preparation-woodward-ok",
    title: "How to Prepare Your Woodward Lawn for Fall and Winter",
    description: "Prepare a Woodward lawn for colder weather with sensible mowing, leaf removal, cleanup, and equipment planning.",
    category: "Lawn Care",
    published: "2026-06-05",
    readTime: "6 min read",
    image: "/images/work/lawn-after.jpg",
    imageAlt: "Neatly maintained lawn prepared for the end of the growing season",
    keywords: ["fall lawn care Woodward", "winter lawn preparation Oklahoma", "final mow tips"],
    lead: "Fall lawn care is not about forcing warm-season grass to stay green. It is about reducing stress, keeping the surface clean, and entering winter without thick debris, ragged edges, or neglected equipment.",
    sections: [
      { heading: "Keep mowing while growth continues", body: "Do not stop because the calendar says fall. Continue mowing while the grass is actively growing, then allow the interval to stretch naturally. Avoid a dramatic final scalp that exposes soil and crowns." },
      { heading: "Keep leaves and debris from matting", body: "A light layer of chopped leaves may disappear quickly, but thick wet piles block light and air. Wind tends to collect leaves against fences, foundations, shrubs, and drainage paths, so inspect those zones regularly." },
      { heading: "Finish with clean edges and a property walk", body: "Trim hard-to-reach growth, clean bed borders, pick up limbs, and note repairs for winter. Drain or protect irrigation components as appropriate and service equipment before it sits unused." },
    ],
    tips: ["Mow until active growth stops.", "Avoid leaving deep leaf piles on turf.", "Clear drainage routes before winter precipitation.", "Use winter to plan bed and brush projects."],
    clmNote: "Combs Land Management handles final mowing, leaf and debris cleanup, edging, and winter property resets for Woodward homes, businesses, rentals, and land.",
    faq: [["Should the final cut be very short?", "No. A severe scalp can stress turf and expose soil. Use a sensible height for the grass and conditions."], ["Can leaves stay in garden beds?", "A light, managed layer can have value, but deep wet piles around crowns and trunks can create problems."]],
    source: sources.lawn,
  },
  {
    slug: "professional-edging-curb-appeal-woodward",
    title: "Why Clean Edging Changes the Look of a Woodward Property",
    description: "Learn why edging drives, sidewalks, and beds creates stronger curb appeal and a longer-lasting finished appearance.",
    category: "Lawn Care",
    published: "2026-05-29",
    readTime: "5 min read",
    image: "/images/about-edging.jpeg",
    imageAlt: "Crew member creating a clean lawn edge beside a sidewalk",
    keywords: ["lawn edging Woodward", "curb appeal lawn care", "sidewalk edging"],
    lead: "A lawn can be evenly mowed and still look unfinished. The eye reads boundaries first, so a clean line along the drive, walk, curb, and garden bed makes the entire property appear more intentional.",
    sections: [
      { heading: "Edging defines the maintained area", body: "Grass creeping over concrete softens every line. Restoring the edge reveals the actual shape of the walkway and creates contrast between turf and hard surface. On corner lots and front walks, that contrast is visible from a distance." },
      { heading: "Bed edges control visual clutter", body: "A defined bed border keeps turf runners and mulch from blending together. It also makes routine weeding and mulch touchups easier because the boundary is obvious." },
      { heading: "The final cleanup matters", body: "Edging without blowing down the property leaves soil and clippings on the surface. A professional finish includes cleanup around walks, porches, drives, curbs, and entrances." },
    ],
    tips: ["Follow the original hard-surface line.", "Avoid cutting a wider trench every visit.", "Pair edging with trimming around posts and fences.", "Blow debris back toward turf before the final collection pass."],
    clmNote: "Combs Land Management includes detail work in its Woodward lawn service because mowing alone is not the finished product. Sharp edges and clean hard surfaces are what make the result pop.",
    faq: [["How often should sidewalks be edged?", "Frequency depends on grass growth and the desired appearance. Active bermudagrass may need more regular attention than slower-growing turf."], ["Does edging help garden beds?", "Yes. A defined edge separates turf from mulch and makes the bed easier to maintain."]],
  },
  {
    slug: "commercial-lawn-maintenance-checklist-woodward",
    title: "A Commercial Lawn Maintenance Checklist for Woodward Businesses",
    description: "A practical property maintenance checklist for Woodward offices, storefronts, rentals, churches, and commercial sites.",
    category: "Lawn Care",
    published: "2026-05-22",
    readTime: "7 min read",
    image: "/images/home-hero.jpg",
    imageAlt: "Large professionally maintained lawn suitable for a commercial property",
    keywords: ["commercial lawn care Woodward", "business property maintenance", "commercial mowing checklist"],
    lead: "Commercial lawn care has a different standard than a backyard. Entrances, signs, parking edges, pedestrian routes, and trash areas all shape the customer's first impression. A good maintenance plan covers the whole arrival experience.",
    sections: [
      { heading: "Prioritize entrances and sight lines", body: "Keep grass, weeds, and shrubs from blocking signs, doors, sidewalks, and vehicle visibility. The front approach should receive the most consistent detail, especially before busy hours or customer events." },
      { heading: "Control clippings and debris", body: "Clippings on parking lots and walks look messy and can become slippery when wet. Litter, windblown material, and storm debris should be included in the property walk rather than ignored because they are not grass." },
      { heading: "Document recurring trouble spots", body: "Low areas, broken irrigation, vehicle tracks, shade, and utility access can create repeat problems. Keep a short site note so the crew knows where to slow down, avoid damage, and report changes." },
    ],
    tips: ["Schedule work around customer traffic.", "Keep fire lanes and utility access clear.", "Inspect signs and entrances every visit.", "Use one contact for approvals and service changes."],
    clmNote: "Combs Land Management serves Woodward commercial properties with recurring mowing, cleanup, bed care, brush work, and small-fleet detailing. One local crew simplifies scheduling and accountability.",
    faq: [["Can service happen outside business hours?", "Scheduling depends on route and property needs, but access and customer traffic can be discussed during the quote."], ["Can cleanup and beds be included?", "Yes. A commercial plan can combine mowing, edging, debris cleanup, garden bed care, and brush clearing."]],
  },
  {
    slug: "mulch-depth-garden-beds-oklahoma",
    title: "The Right Mulch Depth for Garden Beds in Northwest Oklahoma",
    description: "Use the right mulch depth to reduce weeds, conserve moisture, and protect plants without creating mulch volcanoes.",
    category: "Garden Beds",
    published: "2026-05-15",
    readTime: "6 min read",
    image: "/images/work/garden-after.jpg",
    imageAlt: "Freshly edged garden bed with an even mulch layer",
    keywords: ["mulch depth Oklahoma", "garden beds Woodward", "mulch installation"],
    lead: "Mulch is one of the simplest ways to improve a garden bed, but more is not always better. An even layer can slow moisture loss and suppress weeds. A deep pile against a trunk or plant crown can hold excess moisture where it does not belong.",
    sections: [
      { heading: "Aim for an even functional layer", body: "OSU Extension recommends roughly two to three inches near many landscape plants, with coarse materials sometimes applied slightly deeper than fine materials. Measure after the mulch settles instead of judging only by the number of bags used." },
      { heading: "Keep mulch away from trunks and crowns", body: "Do not mound mulch against tree bark or bury the base of shrubs. Leave breathing room around trunks and plant crowns so moisture does not stay trapped against living tissue." },
      { heading: "Prepare the bed before adding more", body: "Pull weeds, redefine the edge, remove trash, and break up compacted old mulch before topping off. Repeatedly adding fresh material without checking existing depth can create an oversized mound." },
    ],
    tips: ["Measure existing mulch before ordering more.", "Use a clean edge to keep material in the bed.", "Leave space around trunks and stems.", "Refresh thin areas instead of covering the entire bed automatically."],
    clmNote: "Combs Land Management refreshes Woodward garden beds from the ground up: cleanup, weeding, edging, mulch placement, and a clean final pass. The goal is a bed that works better and looks finished.",
    faq: [["How deep should mulch be?", "For many landscape beds, a two to three inch layer is a useful target, adjusted for material texture and existing depth."], ["Should old mulch be removed?", "Not always. Loosen and inspect it first. Remove excess, contaminated, or badly matted material before adding more."]],
    source: sources.mulch,
  },
  {
    slug: "spring-garden-bed-refresh-woodward",
    title: "How to Refresh Garden Beds in Spring in Woodward",
    description: "A step-by-step spring garden bed reset for Woodward properties, from cleanup and edging to mulch and final watering.",
    category: "Garden Beds",
    published: "2026-05-08",
    readTime: "7 min read",
    image: "/images/work/garden-before.jpg",
    imageAlt: "Garden bed before a seasonal cleanup and mulch refresh",
    keywords: ["spring garden cleanup Woodward", "garden bed refresh", "landscaping Woodward OK"],
    lead: "Spring beds often look worse than they really are. Dead annual growth, windblown leaves, faded mulch, and blurred edges can hide healthy perennials and shrubs. A deliberate reset restores structure before planting anything new.",
    sections: [
      { heading: "Clean before you plant", body: "Remove trash, sticks, dead annual material, and weeds. Cut back plants only when it is appropriate for that species and season. Cleaning first prevents new plants from being installed into a bed that still has drainage or weed problems." },
      { heading: "Restore the shape of the bed", body: "Follow the home's architecture and the existing landscape line. Redefine edges with smooth curves or straight runs instead of adding random pockets. A strong bed shape has more visual impact than filling every open spot." },
      { heading: "Finish with mulch and water", body: "After planting and cleanup, apply an even mulch layer without burying crowns or piling around trunks. Water new plants thoroughly and confirm that irrigation reaches the full root zone." },
    ],
    tips: ["Mark perennials before aggressive cleanup.", "Remove weeds before they set seed.", "Check irrigation while the bed is open.", "Choose a limited plant palette for a cleaner design."],
    clmNote: "Combs Land Management gives Woodward beds a complete spring reset, including weed removal, reshaped edges, mulch, light shrub cleanup, and seasonal planting where appropriate.",
    faq: [["Should mulch go down before planting?", "It is usually easier to complete planting and soil work first, then apply mulch around the finished layout."], ["How do I keep the bed looking clean longer?", "A defined edge, adequate mulch, timely weed removal, and plants matched to the site make the biggest difference."]],
    source: sources.mulch,
  },
  {
    slug: "low-maintenance-landscaping-woodward-ok",
    title: "Low-Maintenance Landscaping Ideas for Woodward Homes",
    description: "Create a cleaner, lower-maintenance Woodward landscape with practical plant grouping, mulch, defined edges, and useful turf.",
    category: "Garden Beds",
    published: "2026-05-01",
    readTime: "7 min read",
    image: "/images/work/garden-after.jpg",
    imageAlt: "Simple low-maintenance landscape bed with clean edging",
    keywords: ["low maintenance landscaping Woodward", "Oklahoma landscape ideas", "easy garden beds"],
    lead: "Low maintenance does not mean no maintenance. It means designing the property so routine work is predictable, access is easy, and every part of the landscape has a clear purpose.",
    sections: [
      { heading: "Use turf where it is useful", body: "Keep lawn in areas used for play, circulation, curb appeal, or erosion control. Narrow strips, steep corners, and spaces blocked by equipment may be better handled with beds, groundcover, or a different surface." },
      { heading: "Group plants by water and sun needs", body: "Plants with similar needs are easier to water correctly. Put sun-loving, drought-tolerant plants together and reserve higher-water selections for practical, visible zones where irrigation can reach them efficiently." },
      { heading: "Design for the mower and the person maintaining it", body: "Wide curves, accessible bed edges, clear gates, and enough room around obstacles reduce trimming time. Avoid tiny turf pockets and shapes that require constant hand work." },
    ],
    tips: ["Limit the number of bed shapes.", "Repeat a small group of reliable plants.", "Use mulch to reduce bare soil and weeds.", "Leave equipment access to every maintained area."],
    clmNote: "Combs Land Management helps Woodward homeowners simplify overgrown or fussy landscapes. Cleanup, new edges, mulch, selective clearing, and a practical mowing plan can dramatically reduce weekly work.",
    faq: [["Does low maintenance mean removing all lawn?", "No. Functional turf can be valuable. The goal is to keep it where it serves a purpose and is practical to maintain."], ["What is the fastest visual improvement?", "Cleaning bed edges, removing weeds, simplifying clutter, and refreshing mulch usually create an immediate change."]],
    source: sources.water,
  },
  {
    slug: "water-wise-garden-beds-woodward",
    title: "How to Build Water-Wise Garden Beds in Woodward",
    description: "Plan Woodward garden beds that use water efficiently through plant selection, grouping, mulch, soil preparation, and irrigation checks.",
    category: "Garden Beds",
    published: "2026-04-24",
    readTime: "7 min read",
    image: "/images/work/garden-after.jpg",
    imageAlt: "Mulched landscape bed designed to retain moisture",
    keywords: ["water wise landscaping Woodward", "drought tolerant garden Oklahoma", "efficient garden beds"],
    lead: "A water-wise bed can still have color, texture, and a polished look. The difference is that plant choice, soil coverage, and irrigation are planned around northwest Oklahoma's variable rainfall instead of fighting it.",
    sections: [
      { heading: "Start with the site's real conditions", body: "Track sun, reflected heat, drainage, and wind exposure. A plant that succeeds on the east side of a house may struggle beside a west-facing brick wall. Match the plant to the spot before changing the watering schedule." },
      { heading: "Group plants with similar needs", body: "Hydrozoning keeps drought-tolerant plants from being overwatered just to support a thirstier neighbor. It also makes drip lines and hand watering easier to manage." },
      { heading: "Cover and protect the soil", body: "Mulch slows evaporation, reduces erosion, and limits weed competition. Keep an even layer, leave room around stems and trunks, and replenish only where the material has broken down or washed away." },
    ],
    tips: ["Water early in the morning.", "Use drip or soaker delivery where practical.", "Repair leaks and misaligned emitters.", "Choose plants for mature size to avoid constant pruning."],
    clmNote: "Combs Land Management can reset Woodward beds for more efficient care with cleanup, weed removal, defined edges, practical mulch depth, and a simpler plant layout.",
    faq: [["Are drought-tolerant plants maintenance free?", "No. They still need establishment water, occasional cleanup, and site-appropriate care, but they can reduce ongoing water demand."], ["Does mulch save water?", "Yes. OSU Extension notes that mulch can reduce soil moisture loss, moderate temperature, and suppress weed competition."]],
    source: sources.water,
  },
  {
    slug: "garden-bed-weed-control-woodward",
    title: "How to Keep Weeds Out of Woodward Garden Beds",
    description: "A practical weed-control routine for Woodward garden beds using early removal, mulch, clean edges, and regular inspection.",
    category: "Garden Beds",
    published: "2026-04-17",
    readTime: "6 min read",
    image: "/images/work/garden-before.jpg",
    imageAlt: "Landscape bed ready for weed removal and fresh edging",
    keywords: ["garden bed weed control Woodward", "mulch weeds Oklahoma", "landscape bed maintenance"],
    lead: "The easiest weed to remove is the one that has not produced seed or built a deep root system. A small, regular maintenance pass is faster and less disruptive than waiting until weeds blend into every plant.",
    sections: [
      { heading: "Remove weeds while they are young", body: "Pull after rain or light watering when soil releases roots more easily. Remove the entire root where possible and carry seed heads out of the bed instead of dropping them nearby." },
      { heading: "Close open soil with the right mulch layer", body: "Mulch blocks light from many annual weed seeds and makes new growth easier to spot. Thin areas invite weeds, while excessive depth can create moisture and plant-health problems." },
      { heading: "Control the edges", body: "Many bed weeds are actually turf and runners crossing a weak border. A defined edge makes it easier to see encroachment early and prevents the bed from slowly losing its shape." },
    ],
    tips: ["Inspect after warm rain.", "Remove seed heads before moving the plant.", "Do not bury established weeds under new mulch.", "Keep tools clean when moving between problem areas."],
    clmNote: "Combs Land Management provides Woodward bed cleanup, hand weeding, edge restoration, mulch refreshes, and recurring property care so a small problem does not become a full bed renovation.",
    faq: [["Will mulch stop every weed?", "No. It reduces many annual weeds, but windblown seeds and persistent roots still require inspection and removal."], ["Can I just cover weeds with more mulch?", "That often leaves established roots in place and can create excessive mulch depth. Remove weeds first."]],
    source: sources.mulch,
  },
  {
    slug: "protect-trees-from-mowers-trimmers",
    title: "Protecting Trees from Mowers and String Trimmers",
    description: "Prevent avoidable tree damage with clean mulch rings, defined edges, and better mowing access around Woodward landscapes.",
    category: "Garden Beds",
    published: "2026-04-10",
    readTime: "5 min read",
    image: "/images/about-edging.jpeg",
    imageAlt: "Careful trimming beside a maintained lawn and landscape edge",
    keywords: ["protect trees from string trimmer", "tree mulch ring Woodward", "landscape maintenance"],
    lead: "Repeated contact from a mower deck or string trimmer can damage bark around the base of a tree. The injury may look minor at first, but the same spot is often hit again every week. A simple maintenance buffer protects the tree and makes mowing easier.",
    sections: [
      { heading: "Create a clear no-equipment zone", body: "A defined mulch ring keeps mower tires and trimmer line away from the trunk. Size the ring so equipment can follow a smooth path instead of squeezing through a narrow gap." },
      { heading: "Keep mulch off the bark", body: "Spread mulch evenly over the soil but leave visible space around the trunk flare. Piling material against bark can hold moisture and hide damage." },
      { heading: "Inspect stakes, guards, and ties", body: "Temporary protection can become a problem when it is forgotten. Remove or adjust ties that are tight, check guards for trapped moisture, and make sure stakes are still needed." },
    ],
    tips: ["Use a smooth bed edge around the tree.", "Never strike exposed roots with equipment.", "Leave the trunk flare visible.", "Report fresh bark damage before it is hit again."],
    clmNote: "Combs Land Management crews pay attention to the details around trees, beds, posts, and fences. Woodward property care should improve the landscape without creating preventable damage.",
    faq: [["How large should a mulch ring be?", "Larger rings generally provide more protection and reduce trimming, but the right size depends on the tree and landscape layout."], ["Can mulch touch the tree trunk?", "Keep mulch pulled back from the bark and trunk flare rather than forming a mound against it."]],
    source: sources.mulch,
  },
  {
    slug: "rental-property-curb-appeal-woodward",
    title: "Fast Curb Appeal Wins for Woodward Rental Properties",
    description: "Improve a Woodward rental property's first impression with focused mowing, cleanup, bed work, brush removal, and entry detailing.",
    category: "Property Cleanup",
    published: "2026-04-03",
    readTime: "6 min read",
    image: "/images/work/cleanup-after.jpg",
    imageAlt: "Clean rental property yard after a complete exterior reset",
    keywords: ["rental property cleanup Woodward", "rental curb appeal", "property manager lawn care"],
    lead: "A rental does not need an expensive landscape redesign to feel cared for. Prospective tenants notice access, cleanliness, edges, and whether the property feels manageable. Focused cleanup can change that impression quickly.",
    sections: [
      { heading: "Make the approach feel clear", body: "Mow and edge the front lawn, clear the walk, trim growth away from steps and doors, and remove debris from parking areas. The route from vehicle to entrance should look safe and intentional." },
      { heading: "Simplify neglected beds", body: "Remove weeds, dead annuals, broken edging, and scattered material. A simple clean bed with fresh mulch often looks better than a crowded bed full of struggling plants." },
      { heading: "Handle the back and side yards", body: "Tenants will inspect gates, fence lines, outdoor storage areas, and the backyard. Clear dumped material, low limbs, brush, and hidden trip hazards before showings." },
    ],
    tips: ["Prioritize the entry and parking area.", "Remove all debris instead of moving it behind the fence.", "Use simple, repeatable landscape choices.", "Photograph the finished condition for records."],
    clmNote: "Combs Land Management helps Woodward landlords and property managers reset rentals between tenants with mowing, hauling, yard cleanup, bed work, and brush clearing from one local crew.",
    faq: [["What creates the fastest improvement?", "Mowing, edging, debris removal, a clean entry, and simplified beds usually create the strongest immediate change."], ["Can CLM handle one-time rental cleanups?", "Yes. Combs Land Management offers single-visit cleanup as well as recurring property care."]],
  },
  {
    slug: "storm-debris-cleanup-safety-woodward",
    title: "Storm Debris Cleanup Safety for Woodward Property Owners",
    description: "Know what to inspect after wind, hail, or ice and when storm debris requires professional help instead of a weekend cleanup.",
    category: "Property Cleanup",
    published: "2026-03-27",
    readTime: "8 min read",
    image: "/images/work/cleanup-before.jpg",
    imageAlt: "Storm limbs and yard debris before professional cleanup",
    keywords: ["storm cleanup Woodward", "storm debris removal Oklahoma", "tree limb cleanup safety"],
    lead: "Oklahoma storms can leave a property looking like a simple pile of branches when the real risk is overhead. Before cutting or dragging anything, slow down and identify power lines, hanging limbs, split trunks, blocked access, and unstable material.",
    sections: [
      { heading: "Look up before looking down", body: "Broken limbs can remain lodged in a canopy after the storm passes. Stay out from under hanging material and keep people away from the drop zone. If a limb is near a power line, treat the area as dangerous and contact the utility." },
      { heading: "Separate cleanup from tree work", body: "Ground debris that is clear of hazards may be manageable. Hung limbs, heavy trunks, tensioned branches, and damaged trees require different equipment and judgment. Do not assume a chainsaw makes every situation safe." },
      { heading: "Keep emergency access open", body: "Prioritize drives, gates, sidewalks, and routes used by residents or responders. Stack material only where it will not block visibility, drainage, or equipment access, and arrange hauling before the pile spreads again." },
    ],
    tips: ["Photograph the property before moving major debris.", "Wear eye, hand, foot, and hearing protection.", "Never work near downed lines.", "Keep children and pets away from the cleanup zone."],
    clmNote: "Combs Land Management handles ground-level storm debris removal and full property cleanup in the Woodward area. For dangerous overhead tree work, the safest next step may be a qualified tree professional or utility crew.",
    faq: [["Can I cut a limb that is under tension?", "Tensioned wood can move suddenly and unpredictably. Leave it to someone with the equipment and training to manage the load."], ["What should be cleared first?", "Start with hazards and essential access, then move to large debris, smaller material, and the final rake and blow-down."]],
    source: sources.storm,
  },
  {
    slug: "yard-cleanup-after-high-winds-woodward",
    title: "How to Reset a Yard After High Winds in Woodward",
    description: "A practical sequence for cleaning fence lines, beds, turf, drives, and drainage areas after northwest Oklahoma wind.",
    category: "Property Cleanup",
    published: "2026-03-20",
    readTime: "6 min read",
    image: "/images/work/cleanup-after.jpg",
    imageAlt: "Yard restored after windblown debris was removed",
    keywords: ["wind cleanup Woodward", "yard debris removal", "property cleanup Oklahoma"],
    lead: "Wind spreads work across the entire property. Trash catches in shrubs, leaves pack against fences, limbs scatter across turf, and lightweight items move into neighboring areas. The fastest cleanup follows a sequence instead of chasing individual pieces.",
    sections: [
      { heading: "Secure the property first", body: "Bring in loose furniture, bins, toys, and material that can move again. Check gates, panels, and temporary covers before starting the cosmetic cleanup." },
      { heading: "Clear collection points", body: "Work fence lines, corners, shrubs, bed edges, downspouts, and drainage paths where wind naturally deposits material. Bag light debris as you go so it does not blow back across finished areas." },
      { heading: "Finish turf and hard surfaces last", body: "After branches and bulk material are removed, mow or rake the lawn as needed, then blow walks and drives. A final pass from the back of the property toward the loading area avoids reworking clean zones." },
    ],
    tips: ["Use heavy bags or covered containers.", "Check roof-edge and gutter discharge areas from the ground.", "Clear storm drains and culvert entrances.", "Confirm all gates latch before leaving."],
    clmNote: "Combs Land Management provides complete Woodward yard cleanup and hauling after wind events, including fence-line collection, limb removal, turf cleanup, and a clean final pass.",
    faq: [["Why clean fence lines first?", "Windblown material naturally collects there and can blow back across the property if it is left until later."], ["Can cleanup be combined with mowing?", "Yes. Once debris is safely removed, mowing and edging can complete the reset."]],
  },
  {
    slug: "fall-leaf-cleanup-woodward-ok",
    title: "Fall Leaf Cleanup Without Wasting a Weekend",
    description: "A better fall leaf cleanup plan for Woodward lawns, beds, fence lines, gutters, and drainage areas.",
    category: "Property Cleanup",
    published: "2026-03-13",
    readTime: "6 min read",
    image: "/images/work/cleanup-before.jpg",
    imageAlt: "Leaf and yard debris gathered before removal",
    keywords: ["leaf cleanup Woodward", "fall yard cleanup Oklahoma", "leaf removal service"],
    lead: "Leaf cleanup becomes frustrating when the property is cleaned in the wrong order or the wind picks up before material is contained. A simple zone plan keeps the work moving and protects turf from thick, wet mats.",
    sections: [
      { heading: "Start at structures and beds", body: "Move leaves away from porches, foundations, shrubs, and bed corners first. These tight zones usually require hand work and can refill open turf if they are saved for last." },
      { heading: "Move material with the wind when possible", body: "Choose a central collection direction and work in sections. Avoid creating one enormous loose pile early in the day. Bag, tarp, mulch, or load material in manageable stages." },
      { heading: "Inspect turf before the final mow", body: "Thick leaves hide limbs, rocks, toys, and uneven ground. Remove hazards before mowing. A final cut can collect light remaining material and leave the property clean going into winter." },
    ],
    tips: ["Work in smaller zones.", "Keep wet leaves off steps and walks.", "Clear drainage routes before rain.", "Do not leave heavy leaf mats on turf for weeks."],
    clmNote: "Combs Land Management offers fall cleanup and debris removal across Woodward County. The crew can combine leaf collection, final mowing, edging, bed cleanup, and hauling in one visit.",
    faq: [["Can leaves be mulched into the lawn?", "A light layer can often be chopped finely, but thick mats should be removed so they do not block light and air."], ["Do leaves need to come out of beds?", "Remove deep, wet piles and material packed against plant crowns or structures. A managed layer may be useful in some beds."]],
  },
  {
    slug: "move-out-yard-cleanup-woodward",
    title: "The Move-Out Yard Cleanup Checklist for Woodward Rentals",
    description: "Use this exterior move-out checklist to clear trash, mow, edge, reset beds, open access, and document the finished property.",
    category: "Property Cleanup",
    published: "2026-03-06",
    readTime: "7 min read",
    image: "/images/work/cleanup-after.jpg",
    imageAlt: "Rental yard after complete cleanup and mowing",
    keywords: ["move out cleanup Woodward", "rental yard cleanup", "property turnover service"],
    lead: "Exterior turnover work often starts after the keys are returned and the next deadline is already close. A written checklist keeps obvious items from being missed and helps owners document the property's condition.",
    sections: [
      { heading: "Remove abandoned material", body: "Check behind sheds, along fences, near trash areas, under porches, and beside gates. Separate prohibited or hazardous material instead of mixing everything into a general debris load." },
      { heading: "Restore normal access", body: "Open walks, drives, meters, gates, exterior equipment, and service panels. Cut back growth that blocks entry or visibility and remove trip hazards from common routes." },
      { heading: "Finish the landscape and document it", body: "Mow, trim, edge, clean beds, and blow hard surfaces. Photograph each side of the home, the yard, gates, and completed debris areas before the next occupant moves in." },
    ],
    tips: ["Use the same checklist for every turnover.", "Photograph hidden debris before removal.", "Confirm utility access is clear.", "Schedule recurring care if the property will sit vacant."],
    clmNote: "Combs Land Management helps Woodward property managers complete exterior turnovers quickly with hauling, mowing, cleanup, bed resets, and brush clearing.",
    faq: [["Can a cleanup happen while the property is vacant?", "Yes, as long as access and authorization are arranged in advance."], ["What if the yard is severely overgrown?", "The work may need an initial overgrowth reset followed by a finish mow and cleanup."]],
  },
  {
    slug: "prepare-yard-home-listing-woodward",
    title: "How to Prepare a Woodward Yard Before Listing a Home",
    description: "Focus exterior cleanup dollars where buyers notice them most: access, lawn edges, beds, debris, fence lines, and the front entry.",
    category: "Property Cleanup",
    published: "2026-02-27",
    readTime: "6 min read",
    image: "/images/work/lawn-after.jpg",
    imageAlt: "Clean front lawn with strong curb appeal before a home listing",
    keywords: ["curb appeal Woodward home", "yard cleanup before selling", "listing preparation"],
    lead: "Buyers form an opinion before they enter the house. The best pre-listing yard work does not try to reinvent the landscape. It removes distractions, clarifies the property's shape, and makes routine care look manageable.",
    sections: [
      { heading: "Clean the arrival view", body: "Mow and edge the front lawn, clear the drive and walk, remove empty pots and broken décor, and trim growth away from the address and entrance. Make sure photos show a clear path to the door." },
      { heading: "Simplify beds and fence lines", body: "Pull weeds, remove dead plants, define bed edges, refresh thin mulch, and clear brush that makes the yard feel smaller. Avoid last-minute planting that does not match the site's water and sun conditions." },
      { heading: "Remove evidence of unfinished work", body: "Haul away branches, scrap material, old landscape timbers, bags, and half-completed piles. Buyers often read outdoor clutter as future labor and hidden maintenance." },
    ],
    tips: ["Prioritize what appears in listing photos.", "Clean windows, porches, and hard surfaces after yard work.", "Keep gates easy to open.", "Schedule a touch-up before the first weekend of showings."],
    clmNote: "Combs Land Management can give Woodward listings a complete exterior reset with mowing, cleanup, bed work, debris hauling, and brush clearing from one crew.",
    faq: [["Should I install a new landscape before selling?", "Usually a clean, simple, well-maintained property offers better value than a rushed redesign."], ["What should happen first?", "Remove debris and overgrowth first, then mow, edge, refresh beds, and complete the final surface cleanup."]],
  },
  {
    slug: "eastern-redcedar-control-woodward",
    title: "Why Eastern Redcedar Control Matters Near Woodward",
    description: "Understand how eastern redcedar spreads, why early removal costs less, and how Woodward landowners can plan responsible control.",
    category: "Brush Clearing",
    published: "2026-02-20",
    readTime: "8 min read",
    image: "/images/work/brush-before.jpg",
    imageAlt: "Overgrown Oklahoma land with dense woody vegetation",
    keywords: ["eastern redcedar control Woodward", "cedar removal Oklahoma", "brush clearing"],
    lead: "Eastern redcedar can move from scattered seedlings to a dense, expensive problem when maintenance is delayed. It reduces open ground, complicates fence access, and adds volatile fuel to the landscape. Early identification gives landowners more options.",
    sections: [
      { heading: "Small trees become large projects", body: "Young cedars are easier to reach and remove than established trees mixed into fences or dense brush. Walk the property regularly and mark new growth before it disappears into surrounding vegetation." },
      { heading: "Match the method to the property", body: "Mechanical removal, cutting, grazing management, and professionally planned prescribed fire all have different roles. Fire should only be used under a legal, carefully prepared plan with trained people, suitable weather, and appropriate firebreaks." },
      { heading: "Plan what happens after removal", body: "Clearing is not complete when the tree is cut. Decide how material will be handled, how access will be maintained, and how new seedlings will be monitored. A follow-up schedule protects the original investment." },
    ],
    tips: ["Map cedar density before requesting a quote.", "Clear access to gates and fence corners.", "Never burn cedar piles casually.", "Schedule follow-up inspections for new seedlings."],
    clmNote: "Combs Land Management provides mechanical brush and overgrowth clearing around Woodward. The crew can open fence lines, lots, and access areas while helping landowners define a practical maintenance plan.",
    faq: [["Why remove small cedars early?", "Smaller trees are generally easier and less expensive to control before they become dense, tall, or entangled with fences."], ["Does CLM offer prescribed burning?", "Combs Land Management focuses on mechanical clearing and property cleanup. Prescribed fire requires specialized planning, legal compliance, and trained practitioners."]],
    source: sources.cedar,
  },
  {
    slug: "fence-line-clearing-woodward",
    title: "Fence Line Clearing Tips for Woodward Acreage",
    description: "Open visibility, protect fences, and improve maintenance access with a planned fence-line clearing approach.",
    category: "Brush Clearing",
    published: "2026-02-13",
    readTime: "7 min read",
    image: "/images/work/brush-after.jpg",
    imageAlt: "Fence line opened after brush and overgrowth removal",
    keywords: ["fence line clearing Woodward", "acreage brush removal", "property line cleanup"],
    lead: "A fence line can disappear gradually under grass, vines, volunteer trees, and windblown debris. By the time repairs are needed, access is limited and every post becomes harder to inspect. Clearing restores visibility and makes future maintenance faster.",
    sections: [
      { heading: "Define the working width", body: "Decide whether the goal is simple inspection access, equipment travel, firebreak support, or a wider clean corridor. Mark gates, corners, utilities, desirable trees, and areas where neighboring property is close." },
      { heading: "Protect the fence during removal", body: "Wire can be hidden inside trunks and dense growth. Pulling blindly may damage posts or stretch wire. Work methodically and expose the fence before using larger equipment near it." },
      { heading: "Keep the line open", body: "After the initial reset, mow or inspect the corridor on a predictable schedule. Remove volunteer woody growth while it is small and address debris before it becomes embedded again." },
    ],
    tips: ["Locate utilities before digging or grinding.", "Mark wire hidden in vegetation.", "Protect desirable shade trees.", "Plan a recurring pass after the initial clearing."],
    clmNote: "Combs Land Management clears overgrown fence lines throughout the Woodward area using a careful, access-first approach. The finished corridor is easier to inspect, repair, and maintain.",
    faq: [["How wide should a cleared fence line be?", "The width depends on whether you need foot access, mower access, equipment travel, or a broader management goal."], ["Can the removed brush be hauled away?", "Material handling can be included in the quote based on volume, access, and the chosen finish."]],
  },
  {
    slug: "reclaim-overgrown-lot-woodward",
    title: "How to Reclaim an Overgrown Lot in Woodward",
    description: "Turn an overgrown Woodward lot into visible, usable ground with assessment, staged clearing, debris removal, and follow-up mowing.",
    category: "Brush Clearing",
    published: "2026-02-06",
    readTime: "8 min read",
    image: "/images/work/brush-before.jpg",
    imageAlt: "Overgrown lot before brush and volunteer tree removal",
    keywords: ["overgrown lot clearing Woodward", "land clearing Woodward OK", "brush cleanup"],
    lead: "An overgrown lot often contains more than tall vegetation. Hidden wire, dumped debris, holes, stumps, unstable structures, and volunteer trees can change the equipment and sequence needed. The first step is visibility, not speed.",
    sections: [
      { heading: "Assess access and hidden hazards", body: "Walk the perimeter and any safe open routes. Identify utilities, fences, wells, drainage structures, debris, and property boundaries. If the ground cannot be inspected safely, plan an initial access lane before broad clearing." },
      { heading: "Clear in stages", body: "Open entrances and work zones first, remove bulky debris, then address brush and tall growth. A staged approach protects equipment and allows the final finish to match the owner's goal." },
      { heading: "Choose the finished condition", body: "A rough access clearing, a mowable lot, and a presentation-ready property are different scopes. Define whether stumps, cut material, grading, hauling, and recurring maintenance are included." },
    ],
    tips: ["Confirm boundaries before work begins.", "Photograph dumped material and hazards.", "Choose a realistic finish level.", "Plan the first maintenance visit before regrowth starts."],
    clmNote: "Combs Land Management helps Woodward owners reclaim lots, back corners, and unused acreage with brush clearing, debris removal, and a practical path to ongoing maintenance.",
    faq: [["Can an overgrown lot be cleared in one day?", "Small, accessible lots may move quickly, while dense brush, hidden debris, trees, and hauling can require staged work."], ["Will the lot stay clear afterward?", "Not without follow-up. Mowing, spot clearing, and early removal of volunteer growth keep the reset from disappearing."]],
  },
  {
    slug: "brush-clearing-cost-factors-woodward",
    title: "What Affects Brush Clearing Cost in Woodward?",
    description: "Understand the access, density, debris, terrain, hauling, and finish choices that shape a brush clearing quote.",
    category: "Brush Clearing",
    published: "2026-01-30",
    readTime: "7 min read",
    image: "/images/work/brush-after.jpg",
    imageAlt: "Usable open ground after brush clearing",
    keywords: ["brush clearing cost Woodward", "land cleanup quote", "overgrowth removal pricing"],
    lead: "Two areas with the same acreage can require very different amounts of work. A clear quote depends on what is growing, what is hidden, how equipment reaches the site, and what the owner expects the ground to look like when the crew leaves.",
    sections: [
      { heading: "Density and material size", body: "Tall grass and light saplings are different from mature woody growth, dense vines, or cedars mixed together. Larger material requires more cutting, handling, and disposal time." },
      { heading: "Access and terrain", body: "Gate width, slopes, soft ground, overhead lines, fences, nearby buildings, and travel distance across the property affect which equipment can work safely and efficiently." },
      { heading: "Cleanup and finish level", body: "Cutting vegetation is only one part of the scope. Hauling, stacking, chipping, stump treatment, a finish mow, and final surface cleanup can significantly change the result and price." },
    ],
    tips: ["Send wide photos and close-up photos.", "Mark the exact work boundary.", "Describe gate width and ground conditions.", "State whether material must leave the property."],
    clmNote: "Combs Land Management provides free, clear brush clearing quotes around Woodward. Good photos and access details help the crew define the scope before visiting the property.",
    faq: [["Can you quote brush clearing from photos?", "Photos can help with an initial review, but larger or complex properties may need an on-site look."], ["Is hauling always included?", "Not automatically. Material handling and removal should be clearly listed in the quote."]],
  },
  {
    slug: "acreage-maintenance-schedule-woodward",
    title: "A Practical Acreage Maintenance Schedule for Woodward Landowners",
    description: "Keep Woodward acreage accessible with seasonal mowing, fence-line checks, cedar monitoring, storm cleanup, and priority zones.",
    category: "Brush Clearing",
    published: "2026-01-23",
    readTime: "8 min read",
    image: "/images/clm-work-truck.jpg",
    imageAlt: "Combs Land Management work truck prepared for acreage service",
    keywords: ["acreage maintenance Woodward", "land management schedule", "Oklahoma property clearing"],
    lead: "Acreage becomes expensive when every task is delayed until access is lost. A simple schedule keeps gates, drives, fence lines, buildings, and high-use areas open while allowing lower-priority ground to follow a less intensive plan.",
    sections: [
      { heading: "Divide the property into zones", body: "Separate entrances, homesites, barns, fence corridors, utility routes, drainage, and remote acreage. Each zone can have a different mowing or inspection frequency based on risk and use." },
      { heading: "Inspect after major weather", body: "Wind, ice, and heavy rain can block access, damage fences, and move debris into drainage paths. A quick post-storm inspection prevents small access problems from becoming larger ones." },
      { heading: "Control woody growth early", body: "Monitor eastern redcedar, volunteer trees, and brush along fences and open ground. Early removal is easier than reclaiming a dense stand later. Keep a photo record of repeat problem areas." },
    ],
    tips: ["Keep gates and addresses visible.", "Maintain equipment access around structures.", "Inspect fence corners seasonally.", "Schedule cedar and brush checks before growth becomes dense."],
    clmNote: "Combs Land Management works with Woodward acreage owners to combine mowing, cleanup, fence-line clearing, brush removal, and hauling into a realistic property schedule.",
    faq: [["Does every acre need the same maintenance?", "No. Priority zones can receive frequent care while remote or low-use areas follow a seasonal plan."], ["How often should fence lines be checked?", "Inspect at least seasonally and after significant weather, with more frequent checks where growth or livestock pressure is high."]],
    source: sources.cedar,
  },
  {
    slug: "work-truck-detailing-protects-value",
    title: "How Work-Truck Detailing Protects Value in Woodward",
    description: "Learn how regular interior and exterior detailing helps Woodward work trucks present better, clean easier, and retain value.",
    category: "Detailing",
    published: "2026-01-16",
    readTime: "6 min read",
    image: "/images/detailing-truck.jpg",
    imageAlt: "Black work truck after a professional exterior detail",
    keywords: ["truck detailing Woodward", "work truck detail Oklahoma", "fleet detailing"],
    lead: "A work truck does not need to look untouched, but it should look cared for. Dust, road film, spills, sunscreen, food, and jobsite material build up quickly. Regular detailing protects surfaces and keeps the vehicle presentable in front of customers.",
    sections: [
      { heading: "Protect the exterior finish", body: "Frequent washing removes abrasive dirt and road film before it is repeatedly rubbed into paint. A proper exterior detail also reaches trim, wheels, glass, and tight areas that a quick rinse misses." },
      { heading: "Reset the cab", body: "Vacuuming, surface cleaning, glass work, and attention to controls make the truck more comfortable and easier to inspect. Removing buildup early is usually simpler than trying to restore a severely neglected interior." },
      { heading: "Support a professional brand", body: "Customers notice the truck in the drive. A clean vehicle, organized cab, and readable branding reinforce the same attention to detail expected from the work itself." },
    ],
    tips: ["Remove trash at the end of each workday.", "Use floor protection that can be cleaned easily.", "Address spills before heat sets them.", "Schedule a deeper reset before busy seasons."],
    clmNote: "Combs Land Management offers auto and truck detailing in Woodward for daily drivers, work trucks, and small fleets. The same local crew that sharpens properties can help keep the vehicles representing your business sharp too.",
    faq: [["How often should a work truck be detailed?", "Frequency depends on use, but a deeper seasonal reset combined with regular cleaning is a practical starting point."], ["Can small fleets be scheduled together?", "Yes. Ask Combs Land Management about coordinating multiple vehicles and access."]],
  },
  {
    slug: "remove-oklahoma-dust-vehicle-interior",
    title: "How to Keep Oklahoma Dust Out of Your Vehicle Interior",
    description: "Reduce red dirt and fine dust inside Woodward vehicles with simple habits, proper vacuuming, mat care, and regular detailing.",
    category: "Detailing",
    published: "2026-01-09",
    readTime: "6 min read",
    image: "/images/work/detail-after.jpg",
    imageAlt: "Clean vehicle after interior and exterior detailing",
    keywords: ["car detailing Woodward", "remove Oklahoma dust car", "interior detailing tips"],
    lead: "Fine Oklahoma dust travels through open doors, clothing, boots, vents, and every small gap. Wiping it around with a dry towel often moves the problem instead of removing it. A top-to-bottom process works better.",
    sections: [
      { heading: "Control what enters", body: "Shake out mats, knock dirt from footwear, keep work gear contained, and remove trash regularly. Small habits reduce how much material gets ground into carpet and seat seams." },
      { heading: "Clean from high surfaces to low", body: "Dust vents, dash areas, door panels, and seat seams before vacuuming floors. Use tools and products appropriate for each surface, and avoid soaking electronics or leaving slick residue on controls." },
      { heading: "Do not forget filters and glass", body: "A dirty cabin filter can contribute to poor airflow and dust concerns. Interior glass also collects a film that becomes more obvious in low sun, so use a clean towel and a streak-free process." },
    ],
    tips: ["Keep a small trash container in the vehicle.", "Vacuum seat seams before the floor.", "Clean mats outside the cab.", "Use separate towels for glass and interior surfaces."],
    clmNote: "Combs Land Management provides Woodward interior and exterior detailing that reaches beyond a quick wash. It is a full reset for vehicles that live in dust, wind, jobsite dirt, and everyday use.",
    faq: [["Why does dust return so quickly?", "Dust remains in vents, fabrics, seams, mats, and stored gear. A complete top-to-bottom cleaning removes more of the reservoir."], ["Can all interior surfaces use the same cleaner?", "No. Use products suitable for the specific material and avoid heavy residue on steering wheels, pedals, and controls."]],
  },
  {
    slug: "how-often-detail-car-truck-woodward",
    title: "How Often Should You Detail a Car or Truck in Woodward?",
    description: "Choose a practical detailing schedule based on Oklahoma dust, work use, pets, children, parking, and vehicle value.",
    category: "Detailing",
    published: "2026-01-02",
    readTime: "6 min read",
    image: "/images/work/detail-before.jpg",
    imageAlt: "Vehicle before a complete professional detail",
    keywords: ["how often detail car", "truck detailing Woodward OK", "vehicle detail schedule"],
    lead: "There is no perfect detailing interval for every vehicle. A garage-kept commuter and a work truck on gravel roads collect very different wear. The right schedule prevents buildup from becoming damage or a full-day restoration project.",
    sections: [
      { heading: "Start with how the vehicle is used", body: "Worksites, gravel, pets, children, food, smoking, outdoor parking, and frequent passengers all shorten the practical interval. High-use vehicles benefit from small regular cleanups and a deeper reset several times a year." },
      { heading: "Watch for condition triggers", body: "Do not wait for a date if there are spills, odors, embedded mud, heavy road film, or reduced glass visibility. Address those issues promptly, then return to a maintenance rhythm." },
      { heading: "Plan around seasons and events", body: "A spring reset can remove winter buildup, while a fall detail prepares the vehicle for colder weather. Selling, trading, branding a work vehicle, or beginning a busy season are also logical times for a complete detail." },
    ],
    tips: ["Remove trash weekly.", "Treat spills quickly.", "Wash road film before it builds up.", "Schedule deep cleaning before the vehicle becomes uncomfortable."],
    clmNote: "Combs Land Management offers flexible detailing for Woodward cars, trucks, and small fleets. Tell the crew how the vehicle is used and they can help choose a realistic service level.",
    faq: [["Is detailing the same as a car wash?", "No. Detailing includes deeper cleaning and attention to interior, exterior, trim, glass, wheels, seams, and finish areas based on the selected service."], ["Should a work truck be detailed more often?", "Often yes, especially when dust, mud, jobsite material, and customer-facing use are part of the routine."]],
  },
];

export function getBlogPost(slug: string) {
  return blogPosts.find((post) => post.slug === slug);
}

export function getRelatedPosts(post: BlogPost, limit = 3) {
  return blogPosts.filter((candidate) => candidate.category === post.category && candidate.slug !== post.slug).slice(0, limit);
}
